### ISSUE TITLE
is diaumpire output deterministic or probabilistic?

### ISSUE THREAD

**Issue by mremachine1** [Nesvilab/DIA-Umpire#4]
sorry for putting this in the wrong place I don't know where the proper place for questions like this is.
I wanted to know if given the same input file will I get the exact same diaumpire output file each time or will there be differences?

**Comment by fcyu** [comment]
As far as I know, the result is deterministic.

Best,

Fengchao

**Comment by mremachine1** [comment]
Thanks fengchao!
